#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=0
SERVICE_WRITE_PID=0
SERVICE_DAEMONIZE=0

PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin

let wid=0;
tmux_run_command() {

    if [ "$wid" -eq 0 ]; then
        tmux new-session -d -s txvpnd || exit;
    else
        tmux new-window || exit;
    fi;

    tmux send -t txvpnd:$wid "$1" || exit
    tmux send -t txvpnd:$wid  ENTER || exit
    let wid=$wid+1;
}

start() {
    echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
    #service_start $(which tmux)
    tmux_run_command "while true; do txvpnd; sleep 1; done;"
}

stop() {
    #service_stop $(which tmux)
    killall tmux
    echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_all
}
